FROM node:16-alpine3.14

# ENV PORT=3000

# Various libs needed for nodejs build
RUN apk --no-cache add shadow \
    gcc \ 
    musl-dev \
    autoconf \
    automake \
    make \
    libtool \ 
    nasm \
    tiff \
    jpeg \
    zlib \
    zlib-dev \
    file \
    pkgconf \
    bash \
    git \
    openssh \
    tini \
    # python \
    g++

# This has to match docker-compose.yml
WORKDIR /usr/src/web

# EXPOSE 3000

